//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiantBeautyStudio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int IdService { get; set; }
        public int IdStaffer { get; set; }
        public System.DateTime Date { get; set; }
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staffer Staffer { get; set; }
    }
}
